version: '3.7'

services:

  mariadb:
    image: mariadb:10.5.2
    ports:
      - 3306:3306
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_DATABASE: 'checklist-app'

volumes:
  mariadb-volume: